
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public partial class Item
{
    private readonly System.Collections.Generic.Dictionary<int, skill.Skill> _dataMap;
    private readonly System.Collections.Generic.List<skill.Skill> _dataList;
    
    public Item(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, skill.Skill>();
        _dataList = new System.Collections.Generic.List<skill.Skill>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            skill.Skill _v;
            _v = skill.Skill.DeserializeSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, skill.Skill> DataMap => _dataMap;
    public System.Collections.Generic.List<skill.Skill> DataList => _dataList;

    public skill.Skill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public skill.Skill Get(int key) => _dataMap[key];
    public skill.Skill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

