
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.skill
{
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BaseAttackDamage = _buf.ReadInt();
        BaseAttackInterval = _buf.ReadFloat();
        NumberOfTargets = _buf.ReadInt();
        SkillIconPath = _buf.ReadString();
        IsStartingSkill = _buf.ReadBool();
        UnlockLevel = _buf.ReadInt();
    }

    public static Skill DeserializeSkill(ByteBuf _buf)
    {
        return new skill.Skill(_buf);
    }

    /// <summary>
    /// 技能id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能的基础伤害值
    /// </summary>
    public readonly int BaseAttackDamage;
    /// <summary>
    /// 基础冷却时间攻击间隔
    /// </summary>
    public readonly float BaseAttackInterval;
    /// <summary>
    /// 技能每次可以攻击的目标数量
    /// </summary>
    public readonly int NumberOfTargets;
    /// <summary>
    /// 技能图标的精灵路径
    /// </summary>
    public readonly string SkillIconPath;
    /// <summary>
    /// 标记该技能是否为起始技能
    /// </summary>
    public readonly bool IsStartingSkill;
    /// <summary>
    /// 解锁该技能所需的怪物等级
    /// </summary>
    public readonly int UnlockLevel;
   
    public const int __ID__ = 1155715156;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "baseAttackDamage:" + BaseAttackDamage + ","
        + "baseAttackInterval:" + BaseAttackInterval + ","
        + "numberOfTargets:" + NumberOfTargets + ","
        + "skillIconPath:" + SkillIconPath + ","
        + "isStartingSkill:" + IsStartingSkill + ","
        + "unlockLevel:" + UnlockLevel + ","
        + "}";
    }
}

}

