//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------
using UnityEngine;
using UnityEngine.UI;
using TEngine;

namespace GameLogic
{
	[DisallowMultipleComponent]
	public class UI_NetWorkDataComponent : MonoBehaviour
	{
		public Text m_textMessage;
		public Button m_btnConnentServer;
		public Button m_btnSend;
		public Button m_btnSendRPC;
		public Button m_btnPushMessage;
		public Button m_btnReceive;
		public Button m_btnLoginAddress;
		public Button m_btnSendAddress;
		public Button m_btnSendAddressRPC;
		public Button m_btnReceiveAddress;
	}
}
